# Generated by Django 2.2.3 on 2019-07-12 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190712_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Opening_Balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Collection', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Total_Collection', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Expenses', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Closing_Balance', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Profit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='Account',
            new_name='AccountModel',
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ExpenseCategoryModel'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ExpenseCategoryModel'),
        ),
        migrations.CreateModel(
            name='AccountStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Type', models.CharField(choices=[('1', 'Invoice'), ('2', 'Collection')], max_length=50)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Description', models.TextField()),
                ('Credit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Debit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Bank')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Client')),
            ],
        ),
    ]
