# Generated by Django 2.2.3 on 2019-07-12 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_auto_20190713_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile/supplier/%Y/'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_Picture', models.ImageField(blank=True, upload_to='user/profile/%Y/%d/')),
                ('Designation', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=255)),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
