# Generated by Django 2.2.3 on 2019-07-12 19:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20190713_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=50)),
                ('Company_Moto', models.CharField(max_length=50)),
                ('Logo', models.ImageField(upload_to='logo/%Y/')),
                ('Address', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('State', models.CharField(max_length=50)),
                ('Post_Code', models.CharField(max_length=10)),
                ('Currency', models.CharField(max_length=4)),
            ],
        ),
    ]
