# Generated by Django 2.2.3 on 2019-07-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_Picture',
            field=models.ImageField(blank=True, upload_to='user/profile/%Y/'),
        ),
    ]
